name: ThrowableFireballs
main: me.flail.ThrowableFireballs.ThrowableFireballs
version: 1.6.7
author: FlailoftheLord
description: Throw Fireballs, like a Ghast!
api-version: 1.13

commands:
    throwablefireballs:
      description: Main Plugin Command
      usage: /throwablefireballs [reload]
      aliases: [fireballs, fireball, fball]
    icanhasfireball:
      description: lol
      usage: /icanhasfireball
