name: ThrowableFireballs
main: me.flail.ThrowableFireballs.ThrowableFireballs
version: 1.7.10
author: FlailoftheLord
description: Throw Fireballs, like a Ghast!
api-version: 1.15

# dependencies shits
softdepend: [WorldEdit]
loadbefore: [WorldGuard]

commands:
    throwablefireballs:
      description: Main Plugin Command
      usage: /throwablefireballs <reload:updateconfig:get:give:about> <get%amount:give%player-name> [player-name%amount]
      aliases: [fireballs, fireball, fball]
    icanhasfireball:
      description: lol
      usage: /icanhasfireball
      
permissions:
  fireballs.infinite:
    description: won't ever run outta fireballs.
    default: op
  fireballs.op:
    description: use commands
    default: op
  fireballs.throw:
    description: throw ballz ;D
    default: true
  fireballs.commandthrow:
    description: throw ballz using commands
    default: op
  fireballs.bypass:
    description: bypass the cooldown
    default: op
      
 # Permissions
 #   fireballs.op
 #   fireballs.infinite
 #   fireballs.throw
 #   fireballs.commandthrow
 #   fireballs.bypass
